### PR TITLE
Added couple of filters and actions on notification and engine files

### PR DESCRIPTION
**Pull request by g-kanoufi**
Hi Jack, as we talked about those are the small changes i needed for convenience while developing an addon for your awesome plugin.

I guess i might not want to add all the changes in that case i'll keep my fork merged with your updates.

Let me know what you think.

Cheers,

Guillaume

### CODE REVIEW

**Comment by jackmcconnell** [comment]
@g-kanoufi,
If you resolve the merge conflicts from the latest version of BNFW, I'll add this in the next version.

**Comment by g-kanoufi** [comment]
@jackmcconnell done, thanks you.

**Comment by jackmcconnell** [comment]
@g-kanoufi This merge will show in the next version of BNFW.

**Comment by g-kanoufi** [comment]
@jackmcconnell, awesome, thank you!

**Pull request closed without merging**
